### PR TITLE
Use to_hdf overwrite mode w instead of rm

### PR DESCRIPTION
**Pull request by zonca**

### CODE REVIEW

**Comment by AllenDowney** [comment]
Good idea, but I'll apply this change myself rather than try to merge notebooks (ugh!).

Thanks!

**Comment by zonca** [comment]
the `diff` is super clean!

**Comment by AllenDowney** [comment]
Done!

I see you are at SDSC.  I worked there as a sort of pre-doc, from 1995-97.  Loved San Diego!

**Comment by zonca** [comment]
Yeah, love San Diego too!
Thank you for writing this book, it's really tricky to get started on this type of analysis, very useful resource for newcomers

**Pull request merged**
